/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Etat du service
     * @description Sonde utilisee par Docker, Railway et la supervision. Sans authentification, n'interroge aucune dependance externe.
     */
    get: operations["HealthController_verifier"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lister les agents */
    get: operations["AgentsController_lister"];
    put?: never;
    /**
     * Creer un agent
     * @description Cree un compte agent. Le mot de passe temporaire est renvoye une seule fois.
     */
    post: operations["AgentsController_creer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agents/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulter un agent */
    get: operations["AgentsController_trouver"];
    put?: never;
    post?: never;
    /**
     * Archiver un agent
     * @description Suppression douce : la trace reste en base pour audit.
     */
    delete: operations["AgentsController_archiver"];
    options?: never;
    head?: never;
    /** Modifier un agent */
    patch: operations["AgentsController_modifier"];
    trace?: never;
  };
  "/agents/{id}/reinitialiser-mot-de-passe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reinitialiser le mot de passe
     * @description Genere un nouveau mot de passe temporaire, affiche une seule fois.
     */
    post: operations["AgentsController_reinitialiser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/connexion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Se connecter
     * @description Connexion par email ou telephone. Renvoie un jeton a placer dans Authorization: Bearer.
     */
    post: operations["AuthController_connexion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/changer-mot-de-passe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Changer son mot de passe
     * @description Necessite d etre connecte. Obligatoire a la premiere connexion.
     */
    post: operations["AuthController_changerMotDePasse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/coursiers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lister tous les coursiers */
    get: operations["CoursiersController_lister"];
    put?: never;
    /** Recenser un coursier */
    post: operations["CoursiersController_creer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/coursiers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulter un coursier */
    get: operations["CoursiersController_trouver"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Modifier un coursier
     * @description Possible tant que la fiche n est pas validee.
     */
    patch: operations["CoursiersController_modifier"];
    trace?: never;
  };
  "/coursiers/{id}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ajouter une photo ou un document
     * @description Types : PHOTO_IDENTITE, CNI, PERMIS, CARTE_GRISE, ASSURANCE, CARTE_SMT, AUTRE. Formats acceptes : jpg, png, pdf. Max 5 Mo.
     */
    post: operations["CoursiersController_ajouterDocument"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/coursiers/{id}/position": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Mettre a jour la position GPS
     * @description Ajuste uniquement les coordonnees, sans toucher au reste.
     */
    patch: operations["CoursiersController_mettreAJourPosition"];
    trace?: never;
  };
  "/coursiers/{id}/valider": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Valider un coursier
     * @description Reserve aux admins. La fiche entre au registre et devient figee.
     */
    post: operations["CoursiersController_valider"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/coursiers/{id}/rejeter": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rejeter un coursier
     * @description Reserve aux admins. L agent pourra corriger et resoumettre.
     */
    post: operations["CoursiersController_rejeter"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/partenaires": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lister tous les partenaires */
    get: operations["PartenairesController_lister"];
    put?: never;
    /** Recenser un partenaire */
    post: operations["PartenairesController_creer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/partenaires/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulter un partenaire et ses coursiers */
    get: operations["PartenairesController_trouver"];
    put?: never;
    post?: never;
    /**
     * Archiver un partenaire (admin)
     * @description Archive le partenaire et ses coursiers. Trace conservee.
     */
    delete: operations["PartenairesController_archiver"];
    options?: never;
    head?: never;
    /** Modifier un partenaire */
    patch: operations["PartenairesController_modifier"];
    trace?: never;
  };
  "/partenaires/{id}/valider": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Valider un partenaire (admin) */
    post: operations["PartenairesController_valider"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/partenaires/{id}/rejeter": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rejeter un partenaire (admin) */
    post: operations["PartenairesController_rejeter"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/export/coursiers.xlsx": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Telecharger les coursiers en Excel (admin) */
    get: operations["ExportController_coursiersExcel"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/export/coursiers.pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Telecharger les coursiers en PDF (admin) */
    get: operations["ExportController_coursiersPdf"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SanteDto: {
      /**
       * @description Etat global du service
       * @enum {string}
       */
      statut: "ok" | "degrade" | "indisponible";
      /** @example 0.1.0 */
      version: string;
      /** @example development */
      environnement: string;
      /**
       * Format: date-time
       * @example 2026-07-24T14:24:04.000Z
       */
      horodatage: string;
      /**
       * @description Duree depuis le demarrage, en secondes
       * @example 1284
       */
      demarreDepuis: number;
    };
    CreerAgentDto: {
      nom: string;
      telephone: string;
      /** Format: email */
      email: string;
      /**
       * @default AGENT
       * @enum {string}
       */
      role: "AGENT" | "ADMIN";
      motDePasse?: string;
    };
    ModifierAgentDto: {
      nom?: string;
      telephone?: string;
      /** Format: email */
      email?: string;
      /** @enum {string} */
      role?: "AGENT" | "ADMIN";
      /** @enum {string} */
      statut?: "ACTIF" | "SUSPENDU";
    };
    ConnexionDto: {
      /**
       * @description Email ou numero de telephone
       * @example jean@example.com
       */
      identifiant: string;
      motDePasse: string;
    };
    ChangerMotDePasseDto: {
      ancienMotDePasse: string;
      nouveauMotDePasse: unknown & unknown & unknown;
    };
    CreerCoursierDto: {
      nom: string;
      telephone: string;
      cni?: string;
      /** Format: date */
      dateNaissance?: string;
      ville?: string;
      quartier?: string;
      /** @enum {string} */
      typeVehicule:
        "MOTO" | "TRICYCLE" | "VOITURE" | "CAMIONNETTE" | "A_PIED" | "AUTRE";
      plaque?: string;
      marqueModele?: string;
      /** @default false */
      aPermis: boolean;
      /** @enum {string} */
      permisCategorie?: "A" | "B" | "C" | "D" | "E";
      /** @default false */
      aCarteGrise: boolean;
      /** @default false */
      aAssurance: boolean;
      /** @default false */
      aCarteSmt: boolean;
      mobileMoneyNumero?: string;
      /** @enum {string} */
      mobileMoneyOperateur?: "MTN" | "ORANGE";
      latitude?: number;
      longitude?: number;
      adresseGps?: string;
      /** Format: uuid */
      partenaireId?: string;
    };
    ModifierCoursierDto: {
      nom?: string;
      telephone?: string;
      cni?: string;
      /** Format: date */
      dateNaissance?: string;
      ville?: string;
      quartier?: string;
      /** @enum {string} */
      typeVehicule?:
        "MOTO" | "TRICYCLE" | "VOITURE" | "CAMIONNETTE" | "A_PIED" | "AUTRE";
      plaque?: string;
      marqueModele?: string;
      /** @default false */
      aPermis: boolean;
      /** @enum {string} */
      permisCategorie?: "A" | "B" | "C" | "D" | "E";
      /** @default false */
      aCarteGrise: boolean;
      /** @default false */
      aAssurance: boolean;
      /** @default false */
      aCarteSmt: boolean;
      mobileMoneyNumero?: string;
      /** @enum {string} */
      mobileMoneyOperateur?: "MTN" | "ORANGE";
      latitude?: number;
      longitude?: number;
      adresseGps?: string;
      /** Format: uuid */
      partenaireId?: string;
    };
    PositionDto: {
      latitude: number;
      longitude: number;
      adresseGps?: string;
    };
    CreerPartenaireDto: {
      nom: string;
      sigle?: string;
      niu?: string;
      registreCommerce?: string;
      responsableNom: string;
      responsableTelephone: string;
      /** Format: email */
      responsableEmail?: string;
      ville?: string;
      quartier?: string;
      adresse?: string;
      latitude?: number;
      longitude?: number;
      mobileMoneyNumero?: string;
      /** @enum {string} */
      mobileMoneyOperateur?: "MTN" | "ORANGE";
    };
    ModifierPartenaireDto: {
      nom?: string;
      sigle?: string;
      niu?: string;
      registreCommerce?: string;
      responsableNom?: string;
      responsableTelephone?: string;
      /** Format: email */
      responsableEmail?: string;
      ville?: string;
      quartier?: string;
      adresse?: string;
      latitude?: number;
      longitude?: number;
      mobileMoneyNumero?: string;
      /** @enum {string} */
      mobileMoneyOperateur?: "MTN" | "ORANGE";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_verifier: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SanteDto"];
        };
      };
    };
  };
  AgentsController_lister: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AgentsController_creer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreerAgentDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AgentsController_trouver: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AgentsController_archiver: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AgentsController_modifier: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModifierAgentDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AgentsController_reinitialiser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_connexion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnexionDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_changerMotDePasse: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangerMotDePasseDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CoursiersController_lister: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CoursiersController_creer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreerCoursierDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CoursiersController_trouver: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CoursiersController_modifier: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModifierCoursierDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CoursiersController_ajouterDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** @example CNI */
          type?: string;
          /** Format: binary */
          fichier?: string;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CoursiersController_mettreAJourPosition: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PositionDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CoursiersController_valider: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CoursiersController_rejeter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PartenairesController_lister: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PartenairesController_creer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreerPartenaireDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PartenairesController_trouver: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PartenairesController_archiver: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PartenairesController_modifier: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModifierPartenaireDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PartenairesController_valider: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PartenairesController_rejeter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ExportController_coursiersExcel: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ExportController_coursiersPdf: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
